"""add resolved to waste_logs

Revision ID: 19da78f1e167
Revises: f8e2c1a09b3d
Create Date: 2026-02-28 11:51:37.086297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19da78f1e167'
down_revision: Union[str, None] = 'f8e2c1a09b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_logs', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_logs', 'resolved')
    # ### end Alembic commands ###
